import { AuthProvider } from "@/context/auth";
import "@/styles/globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className="font-Montserrat">
      <body>
        <AuthProvider> {children} </AuthProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
